//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uygulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uygulama
    {
        public string Ad { get; set; }
        public string Mail { get; set; }
        public string Sifre { get; set; }
        public string Sehir { get; set; }
        public int ID { get; set; }
        public string YETKİ { get; set; }
    }
}
